-- calling an stored proc for backup of table

config {
  type: "operations",
  name: "backup_stg_distribution_centre_proc",
  schema: dataform.projectConfig.vars.bronzeSchema,
  description: "Distribution center name and location",
  tags: ["distribution_centre" ,"bronze"]
}
CALL `${dataform.projectConfig.vars.myDatabase}.${dataform.projectConfig.vars.bronzeSchema}.sp_backup_table`('stg_distribution_centre_op');