
config {
  type: "table",
  schema: dataform.projectConfig.vars.silver_Schema,
  tags: ["users" ,"silver"],
  description: "users details",
  bigquery: {
     labels: {"type":"dimension"}
  },
  dependencies: ["check_users"]
}


select
id	,	
--${constants.BASE_YEAR},	
first_name,				
last_name,			
email,		
age	,			
gender,				
state,			
street_address,				
postal_code,		
city,	
country,				
latitude,				
longitude,				
traffic_source,				
created_at
  from
  ${ref("stg_users")}