steps:
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['SSH_KEY']
  entrypoint: 'bash'
  args:
  - -c
  - |
    echo "$$SSH_KEY" >> /root/.ssh/id_rsa
    chmod 400 /root/.ssh/id_rsa
    cp known_hosts.github /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Clone the repository
- name: 'gcr.io/cloud-builders/git'
  args:
  - clone
  - --recurse-submodules
  - git@github.com:warunk9/$REPO_NAME
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Checkout Development Branch
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - -c
  - |
    cd $REPO_NAME
    git checkout $BRANCH_NAME

# Run package installation
- name: 'dataformco/dataform:latest'
  args:
  - install
  - /workspace/$REPO_NAME

# Run compilation
- name: 'dataformco/dataform:latest'
  args:
  - compile
  - /workspace/$REPO_NAME

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/github_key/versions/latest
    env: 'SSH_KEY'
