config {
  hasOutput: true,
  type: "operations",
  schema: dataform.projectConfig.vars.defaultSchema,
  tags: ["distribution centre" ,"bronze"]
}
LOAD DATA OVERWRITE ${ self() }
(
    id INTEGER NOT NULL,
    name STRING,
    latitude FLOAT64,
    longitude FLOAT64,
)
FROM FILES (
  format = "CSV",
  field_delimiter = ",",
  skip_leading_rows = 1,
  quote = "",
  uris = ["gs://df_ecom_demo/raw_data/distribution centre/distribution centre_20230811.csv"]
);